# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='scalss',
            new_name='sclass',
        ),
    ]
